// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Input.H>

class GUI {
public:
    GUI();
    Fl_Double_Window *uiw;
private:
    inline void cb_DBG_i(Fl_Button*, void*);
    static void cb_DBG(Fl_Button*, void*);
    inline void cb_SM1_i(Fl_Return_Button*, void*);
    static void cb_SM1(Fl_Return_Button*, void*);
    inline void cb_SM2_i(Fl_Return_Button*, void*);
    static void cb_SM2(Fl_Return_Button*, void*);
    inline void cb_SM3_i(Fl_Return_Button*, void*);
    static void cb_SM3(Fl_Return_Button*, void*);
    inline void cb_AmbientU_i(Fl_Return_Button*, void*);
    static void cb_AmbientU(Fl_Return_Button*, void*);
    inline void cb_AmbientD_i(Fl_Return_Button*, void*);
    static void cb_AmbientD(Fl_Return_Button*, void*);
    inline void cb_SpecularU_i(Fl_Return_Button*, void*);
    static void cb_SpecularU(Fl_Return_Button*, void*);
    inline void cb_SpecularD_i(Fl_Return_Button*, void*);
    static void cb_SpecularD(Fl_Return_Button*, void*);
    inline void cb_Shadow_i(Fl_Return_Button*, void*);
    static void cb_Shadow(Fl_Return_Button*, void*);
    inline void cb_EnvMap_i(Fl_Return_Button*, void*);
    static void cb_EnvMap(Fl_Return_Button*, void*);
public:
    void show();
    void DBG_cb();
    void SM1_cb();
    void SM2_cb();
    void SM3_cb();
    void AmbientU_cb();
    void AmbientD_cb();
    void SpecularU_cb();
    void SpecularD_cb();
    void Shadow_cb();
    void EnvMap_cb();
};
#endif
